/// <reference types="vitest" />

import legacy from '@vitejs/plugin-legacy'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    legacy(),
    // PWA: makes the app installable for on-device testing over real HTTPS
    // (deploy/VPS_HTTPS_TESTING.md). This is a TESTING/DEMO vehicle for the warm
    // path (login → create-run → confirm → end), NOT a production target: a
    // browser gets no background GPS (fixes stop when the screen locks) and prod
    // exposes no WS broker listener. Real telemetry is the native A5 plugin.
    VitePWA({
      // 'prompt', NOT 'autoUpdate'. autoUpdate reloads the page as soon as a new
      // SW activates. The active run lives only in the Pinia run store —
      // resume-active-run-on-boot is still open work pending a backend endpoint
      // (llms.txt) — so an auto-reload mid-run would silently drop the
      // operator's run and stop telemetry. With 'prompt' the new SW waits and
      // lands on the next cold start instead of interrupting a run in progress.
      registerType: 'prompt',
      // Registration is done by hand in src/services/pwa.ts so it can be skipped
      // on native: capacitor.config.ts uses webDir: 'dist', so this same build
      // feeds the Capacitor webview, where a SW causes stale-asset bugs.
      injectRegister: null,
      includeAssets: ['favicon.png', 'pwa/apple-touch-icon-180x180.png'],
      manifest: {
        id: '/',
        name: 'Databús',
        short_name: 'Databús',
        description: 'Cliente de operador para el sistema de transporte Databús',
        lang: 'es',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        categories: ['transportation'],
        // Cyan is the "b" mark's own colour (#00c0f3, sampled from
        // public/logo/databus-mark.png) — the install identity follows the mark.
        theme_color: '#00c0f3',
        // Matches the palette's `secondary`, which SplashPage paints as its
        // background — so the OS splash flows into the app's first paint
        // instead of flashing white. Static by nature: the in-app palette is
        // user-switchable at runtime, the manifest is baked at build time.
        background_color: '#1f2421',
        icons: [
          { src: 'pwa/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            // Cropped to the inner ~80% by Android, so this one is the
            // knocked-out variant: solid brand field, white "b", no ring.
            src: 'pwa/pwa-maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // CRITICAL: the app is deliberately same-origin (VITE_API_BASE_URL=/api,
        // Traefik path-routes /api on the app host to the orchestrator), so
        // without this denylist Workbox's navigation fallback would answer API
        // paths with index.html. Nothing under /api may be cached or faked
        // either: these are live run-lifecycle FSM reads, and showing an
        // operator a stale run state is worse than showing an error.
        navigateFallbackDenylist: [/^\/api/],
        // Precache the shell only. No runtimeCaching for /api — by omission and
        // on purpose.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // Resolve the local in-repo telemetry plugin from source so the app
      // builds without a separate plugin build step (no committed dist/).
      'capacitor-databus-telemetry': path.resolve(
        __dirname,
        './plugins/capacitor-databus-telemetry/src/index.ts',
      ),
    },
  },
  // Dev-only proxy: the browser calls same-origin /api/... and Vite forwards
  // to the Databús orchestrator. This sidesteps CORS (the backend has no
  // django-cors-headers configured for the dev origin). Prod uses an absolute
  // https API URL (native apps have no CORS; prod web is same-origin or CORS'd).
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    // `virtual:pwa-register` is generated by vite-plugin-pwa at build time and
    // does not resolve under vitest — alias it to a stub so services/pwa.ts is
    // testable. Test-only: the real virtual module is untouched in a build.
    alias: {
      'virtual:pwa-register': path.resolve(__dirname, './tests/stubs/pwa-register.ts'),
    },
  }
})
